// Build-time only: generate CSP-compatible ESM validators from frozen schemas.
import Ajv from 'ajv';
import addFormats from 'ajv-formats';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { readFile, writeFile } from 'node:fs/promises';

const ajv = new Ajv({
  allErrors: true,
  strict: false,
  code: { source: true, esm: true },
});
addFormats(ajv, { mode: 'full' });
const names = [
  'card-config',
  'integration-config',
  'command',
  'event',
  'info',
  'assets',
];
for (const name of names)
  ajv.addSchema(
    JSON.parse(await readFile(`contracts/${name}.schema.json`, 'utf8')),
    name,
  );
let code = standaloneCode(
  ajv,
  Object.fromEntries(names.map((name) => [name.replaceAll('-', '_'), name])),
);
// Ajv's ESM output still names two CJS helpers. Resolve these known literal
// expressions explicitly, avoiding differing default-import interop in Vite/Node.
code = code.replaceAll(
  'require("ajv/dist/runtime/ucs2length").default',
  '((value) => [...value].length)',
);
code = code.replaceAll(
  'require("ajv-formats/dist/formats").fullFormats',
  'fullFormats',
);
if (code.includes('require('))
  throw new Error('New standalone helper requires an explicit ESM import');
await writeFile(
  'src/config/validators.js',
  "// Generated by src/config/generate.mjs; do not edit.\nimport { fullFormats } from 'ajv-formats/dist/formats.js';\n" +
    code,
);
