/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface IntegrationConfig {
  schema_version: 1;
  anchor:
    | {
        kind: 'home';
      }
    | {
        kind: 'zone';
        entity_id: string;
      }
    | {
        kind: 'custom';
        latitude: number;
        longitude: number;
      };
  aircraft_provider: 'adsb_fi' | 'adsb_lol';
  aircraft_radius_m: number;
  aircraft_interval_s: number;
  disk_cache_mib: number;
  background_collection: boolean;
  provider_pacing: {
    adsb_fi_min_interval_s: number;
    adsb_lol_min_interval_s: number;
    rainviewer_requests_per_minute: number;
    noaa_requests_per_minute: number;
    dwd_requests_per_minute: number;
  };
  aircraft_radius_unit: 'km' | 'mi' | 'nmi';
}
