/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CardConfig {
  schema_version: 2;
  type: 'custom:aviadilo-map';
  title?: string;
  entry_id?: string | null;
  map?: {
    layout?: 'map' | 'list' | 'combined';
    auto_height?: boolean;
    show_layer_buttons?: boolean;
    show_you_are_here?: boolean;
    height_px?: number;
    anchor?:
      | {
          kind: 'home';
        }
      | {
          kind: 'zone';
          entity_id: string;
        }
      | {
          kind: 'custom';
          latitude: number;
          longitude: number;
        };
    extent_m?: number;
    mode?: 'home-area' | 'fit-people' | 'fit-visible';
    min_zoom?: number;
    max_zoom?: number;
    show_recenter?: boolean;
    idle_return_s?: number | null;
    /**
     * @minItems 0
     * @maxItems 100
     */
    include_zones?: string[];
    extent_unit?: 'km' | 'mi' | 'nmi';
    theme?: 'auto' | 'light' | 'dark';
    [k: string]: unknown;
  };
  layers?: {
    aircraft?: boolean;
    radar?: boolean;
    wind?: boolean;
    people?: boolean;
    [k: string]: unknown;
  };
  radar?: {
    provider?: 'rainviewer' | 'noaa_mrms' | 'noaa_ksox';
    opacity?: number;
    mode?: 'latest' | 'loop';
    history_minutes?: number;
    frame_duration_ms?: number;
    [k: string]: unknown;
  };
  wind?: {
    provider?: 'dwd_icon_global';
    marker_spacing_px?: number;
    marker_size_px?: number;
    particle_count?: number;
    animation_speed?: number;
    trail_length_s?: number;
    opacity?: number;
    speed_unit?: 'km/h' | 'mph' | 'knots' | 'm/s';
    mode?: 'arrows' | 'barbs' | 'particles';
    color?: string;
    [k: string]: unknown;
  };
  people?: {
    /**
     * @minItems 0
     * @maxItems 100
     */
    trackers?: {
      entity_id: string;
      name?: string;
      show_photo?: boolean;
      icon?: string;
      color?: string;
      [k: string]: unknown;
    }[];
    show_labels?: boolean;
    radius_enabled?: boolean;
    radius_m?: number;
    radius_unit?: 'km' | 'mi' | 'nmi';
    anchor?:
      | null
      | (
          | {
              kind: 'home';
            }
          | {
              kind: 'zone';
              entity_id: string;
            }
          | {
              kind: 'custom';
              latitude: number;
              longitude: number;
            }
        );
    accuracy_circles?: boolean;
    max_age_s?: number | null;
    show_stale?: boolean;
    group_overlapping?: boolean;
    [k: string]: unknown;
  };
  aircraft?: {
    show_map?: boolean;
    show_list?: boolean;
    airborne_only?: boolean;
    min_altitude_m?: number | null;
    max_altitude_m?: number | null;
    max_distance_m?: number | null;
    distance_unit?: 'km' | 'mi' | 'nmi';
    altitude_unit?: 'm' | 'ft';
    speed_unit?: 'km/h' | 'mph' | 'knots' | 'm/s';
    label_mode?: 'off' | 'callsign' | 'altitude' | 'callsign-altitude';
    marker_size_px?: number;
    marker_color?: string;
    /**
     * @minItems 0
     * @maxItems 8
     */
    list_columns?: (
      | 'callsign'
      | 'registration'
      | 'aircraft_type'
      | 'altitude'
      | 'speed'
      | 'distance'
      | 'course'
      | 'squawk'
    )[];
    sort?: 'nearest' | 'callsign' | 'altitude' | 'speed';
    list_rows?: number;
    selected_trail_s?: number;
    /**
     * @minItems 0
     * @maxItems 14
     */
    detail_fields?: (
      | 'callsign'
      | 'registration'
      | 'icao'
      | 'aircraft_type'
      | 'category'
      | 'altitude'
      | 'speed'
      | 'course'
      | 'vertical_rate'
      | 'squawk'
      | 'position_age'
      | 'distance'
      | 'ground'
    )[];
    /**
     * @minItems 0
     * @maxItems 10
     */
    types?: (
      | 'airplanes'
      | 'helicopters'
      | 'gliders'
      | 'balloons'
      | 'parachutists'
      | 'ultralights'
      | 'drones'
      | 'spacecraft'
      | 'ground'
      | 'unknown'
    )[];
    [k: string]: unknown;
  };
  freshness?: {
    max_position_age_s?: number;
    stale_retention_s?: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
