/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Asset protocol v1. kind is the parsed route discriminator, never a query parameter. HTTP query keys are schema_version=1, generation, optional entry_id; photo adds entity_id and picture_key. No duplicate or unknown keys. Canonical decimal path components; x,y < 2**z. Authenticated WS aviadilo/subscribe_assets accepts only id/type/schema_version, acknowledges with the standard HA result and sends event {event_type: aviadilo/assets_changed, data: AssetInfo}. Standard HA unsubscribe/disconnect releases subscriptions; limits 4/connection, 16/user, 128 total. Event aviadilo/assets_changed data equals AssetInfo; WS aviadilo/assets_info returns AssetInfo via the standard HA result envelope. Success: PNG with X-Aviadilo-Generation, nosniff, bounded cache headers and validators. Errors: JSON AssetErrorBody and no-store; stale_generation also carries the current generation header. Status mapping: {"invalid_request": 400, "unauthorized": 401, "forbidden": 403, "not_found": 404, "stale_generation": 409, "picture_changed": 409, "busy": 429, "upstream_error": 502, "unavailable": 503}. Frontend admission 8 active/128 pending per connection; backend 8/user and 32 total. Image loading, queues and retention are separate implementation layers.
 */
export type AssetContract =
  | BasemapRequest
  | PhotoRequest
  | AssetInfo
  | AssetsInfoCommand
  | SubscribeAssetsCommand
  | AssetErrorBody;
/**
 * Opaque process-instance UUID hex plus colon and canonical decimal counter (0..999999999999999). Preserve exactly in queries, events and X-Aviadilo-Generation.
 */
export type Generation = string;
export type EntryId = string;
export type PictureKey = string;
export type AssetErrorBody =
  | InvalidRequest
  | Unauthorized
  | Forbidden
  | NotFound
  | StaleGeneration
  | PictureChanged
  | Busy
  | UpstreamError
  | Unavailable;

export interface BasemapRequest {
  kind: 'basemap';
  schema_version: 1;
  generation: Generation;
  entry_id?: EntryId;
  z: number;
  x: number;
  y: number;
}
export interface PhotoRequest {
  kind: 'photo';
  schema_version: 1;
  generation: Generation;
  entry_id?: EntryId;
  entity_id: string;
  picture_key: PictureKey;
}
export interface AssetInfo {
  schema_version: 1;
  generation: Generation;
  entry_id: EntryId;
}
export interface AssetsInfoCommand {
  schema_version: 1;
  id: number;
  type: 'aviadilo/assets_info';
  entry_id?: EntryId;
}
export interface SubscribeAssetsCommand {
  schema_version: 1;
  id: number;
  type: 'aviadilo/subscribe_assets';
}
export interface InvalidRequest {
  schema_version: 1;
  code: 'invalid_request';
  message: 'Invalid asset request';
}
export interface Unauthorized {
  schema_version: 1;
  code: 'unauthorized';
  message: 'Authentication required';
}
export interface Forbidden {
  schema_version: 1;
  code: 'forbidden';
  message: 'Asset access denied';
}
export interface NotFound {
  schema_version: 1;
  code: 'not_found';
  message: 'Asset or entry is unavailable';
}
export interface StaleGeneration {
  schema_version: 1;
  code: 'stale_generation';
  message: 'Asset generation has changed';
  generation: Generation;
}
export interface PictureChanged {
  schema_version: 1;
  code: 'picture_changed';
  message: 'Entity picture has changed';
}
export interface Busy {
  schema_version: 1;
  code: 'busy';
  message: 'Asset capacity reached';
}
export interface UpstreamError {
  schema_version: 1;
  code: 'upstream_error';
  message: 'Asset source is unavailable';
}
export interface Unavailable {
  schema_version: 1;
  code: 'unavailable';
  message: 'Asset service is unavailable';
}
