/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Command =
  | {
      schema_version: 1;
      id: number;
      type: 'aviadilo/info';
      entry_id: string | null;
    }
  | {
      schema_version: 1;
      id: number;
      type: 'aviadilo/subscribe';
      entry_id: string;
      layers: LayerFlags;
      radar_provider: 'rainviewer' | 'noaa_mrms' | 'noaa_ksox';
      viewport: Viewport;
      revision: number;
    }
  | {
      schema_version: 1;
      id: number;
      type: 'aviadilo/update_subscription';
      subscription_id: number;
      entry_id: string;
      layers: LayerFlags;
      radar_provider: 'rainviewer' | 'noaa_mrms' | 'noaa_ksox';
      viewport: Viewport;
      revision: number;
    }
  | {
      schema_version: 1;
      id: number;
      type: 'aviadilo/heartbeat';
      subscription_id: number;
    };

export interface LayerFlags {
  aircraft: boolean;
  radar: boolean;
  wind: boolean;
}
export interface Viewport {
  south: number;
  north: number;
  west: number;
  east: number;
  zoom: number;
}
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SnapshotEvent =
  | {
      schema_version: 1;
      subscription_id: number;
      revision: number;
      kind: 'aircraft';
      provider: 'adsb_fi' | 'adsb_lol';
      fetched_at: string;
      /**
       * @minItems 0
       * @maxItems 10000
       */
      aircraft: Aircraft[];
    }
  | {
      schema_version: 1;
      subscription_id: number;
      revision: number;
      kind: 'radar-manifest';
      provider: 'rainviewer' | 'noaa_mrms' | 'noaa_ksox';
      product: string;
      generated_at: string;
      /**
       * @minItems 0
       * @maxItems 288
       */
      frames: {
        id: string;
        time: string;
      }[];
      native_max_zoom: number;
      attribution: string;
      coverage: Coverage | null;
    }
  | {
      schema_version: 1;
      subscription_id: number;
      revision: number;
      kind: 'wind-grid';
      provider: 'dwd_icon_global';
      coverage_id: string;
      valid_time: string;
      run_time: string | null;
      width: number;
      height: number;
      first_latitude: number;
      first_longitude: number;
      latitude_step: number;
      longitude_step: number;
      crs: 'EPSG:4326';
      row_order: 'north-to-south';
      /**
       * @minItems 1
       * @maxItems 4096
       */
      u_mps: [number | null, ...(number | null)[]];
      /**
       * @minItems 1
       * @maxItems 4096
       */
      v_mps: [number | null, ...(number | null)[]];
      effective_resolution_deg: number;
      attribution: string;
    }
  | {
      schema_version: 1;
      subscription_id: number;
      revision: number;
      kind: 'status';
      /**
       * @minItems 0
       * @maxItems 3
       */
      statuses: {
        layer: 'aircraft' | 'radar' | 'wind';
        state:
          | 'loading'
          | 'current'
          | 'stale'
          | 'unavailable'
          | 'outside-coverage';
        provider:
          | 'adsb_fi'
          | 'adsb_lol'
          | 'rainviewer'
          | 'noaa_mrms'
          | 'noaa_ksox'
          | 'dwd_icon_global';
        last_success: string | null;
        effective_interval_s: number | null;
        message: string | null;
      }[];
    };

export interface Aircraft {
  id: string;
  icao: string | null;
  latitude: number | null;
  longitude: number | null;
  position_age_s: number | null;
  callsign: string | null;
  registration: string | null;
  aircraft_type: string | null;
  category: string | null;
  on_ground: boolean | null;
  altitude_m: number | null;
  speed_mps: number | null;
  course_deg: number | null;
  vertical_rate_mps: number | null;
  squawk: string | null;
}
export interface Coverage {
  bounds: Viewport;
  description: string;
}
export interface Viewport {
  south: number;
  north: number;
  west: number;
  east: number;
  zoom: number;
}
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Info {
  schema_version: 1;
  entry_id: string | null;
  area: {
    latitude: number;
    longitude: number;
    radius_m: number;
  } | null;
  capabilities: {
    /**
     * @minItems 0
     * @maxItems 2
     */
    aircraft: ('adsb_fi' | 'adsb_lol')[];
    /**
     * @minItems 0
     * @maxItems 3
     */
    radar: ('rainviewer' | 'noaa_mrms' | 'noaa_ksox')[];
    /**
     * @minItems 0
     * @maxItems 1
     */
    wind: 'dwd_icon_global'[];
  };
  policies: {
    adsb_fi_min_interval_s: number;
    adsb_lol_min_interval_s: number;
    rainviewer_requests_per_minute: number;
    noaa_requests_per_minute: number;
    dwd_requests_per_minute: number;
  };
  /**
   * @minItems 0
   * @maxItems 3
   */
  statuses: {
    layer: 'aircraft' | 'radar' | 'wind';
    state: 'loading' | 'current' | 'stale' | 'unavailable' | 'outside-coverage';
    provider:
      | 'adsb_fi'
      | 'adsb_lol'
      | 'rainviewer'
      | 'noaa_mrms'
      | 'noaa_ksox'
      | 'dwd_icon_global';
    last_success: string | null;
    effective_interval_s: number | null;
    message: string | null;
  }[];
  heartbeat_s: 20;
  lease_s: 60;
  backend_memory_mib: 64;
}
